### PR TITLE
Enhancements

### LINKED ISSUE #5: Create centralised exception and error handling

### LINKED ISSUE #6: Add Lombock library

### LINKED ISSUE #7: Roles to enum
Remove the table entity of user_role and made it as enum

### PR DESCRIPTION
**Pull request by manojgaonkar8252**
1) Added lombok dependency.
2) Converted roles from table entity to Enum.
3) Custom Exception Handling.
4) Added Slf4j for logging.
5. Added Jackson annotations.

### CODE REVIEW

File: src/main/java/com/nammaexpo/controllers/RegistrationController.java [hunk 1]
```diff
@@ -1,86 +1,62 @@
...
-import org.springframework.security.authentication.AuthenticationManager;
 import org.springframework.security.crypto.password.PasswordEncoder;
-import org.springframework.web.bind.annotation.CrossOrigin;
 import org.springframework.web.bind.annotation.PostMapping;
 import org.springframework.web.bind.annotation.RequestBody;
-import org.springframework.web.bind.annotation.RequestMapping;
 import org.springframework.web.bind.annotation.RestController;
 
+@Slf4j
 //@CrossOrigin(origins = "*", maxAge = 3600)
```
Comment (sidd3sh) [inline src/main/java/com/nammaexpo/controllers/RegistrationController.java]: please uncomment cross origin

File: src/main/java/com/nammaexpo/controllers/LoginController.java [hunk 2]
```diff
@@ -4,54 +4,63 @@
...
-import org.springframework.security.authentication.DisabledException;
 import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
 import org.springframework.security.core.userdetails.UserDetails;
-import org.springframework.web.bind.annotation.*;
+import org.springframework.web.bind.annotation.PostMapping;
+import org.springframework.web.bind.annotation.RequestBody;
+import org.springframework.web.bind.annotation.RestController;
 
+@Slf4j
 //@CrossOrigin(origins = "*", maxAge = 3600)
```
Comment (sidd3sh) [inline src/main/java/com/nammaexpo/controllers/LoginController.java]: please uncomment cross origin

**Review by sidd3sh — CHANGES_REQUESTED** [review]
please allow cross origin
